Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-06, with the labels that each got.

#64 add email to cookie
  server/routers/userRouter.js
Labels: Backend :gear:, Ready for Review 🔍

#66 Feat/#62/eperusteet api
  server/index.js
  server/package.json
  server/routers/eduRouter.js
Labels: Backend :gear:, Feat :new:, Ready for Review 🔍

#104 Routerin uudelleennimeäminen
  server/index.js
  server/routers/eReqRouter.js
Labels: Backend :gear:, Ready for Review 🔍, Refactor :repeat:

#106 for-router-and-model
  server/models/userModel.js
  server/routers/eduRouter.js
Labels: Backend :gear:, Ready for Review 🔍, Refactor :repeat:

#97 Feat/#72/frontend notificationbadge
  client/package-lock.json
  client/src/assets/Internallink.svg
  client/src/components/NotificationBadge/NotificationBadge.jsx
  client/src/components/NotificationBadge/_notificationbadge.scss
  client/src/scss/index.scss
Labels: Ready for Review 🔍, Unassigned ❕, Review Requested 🔍

#111 [Design]: codeowner update + main branch protection rules
  .github/CODEOWNERS
Labels: Chore :construction_worker_man:, Design :art:, Ready for Review 🔍

#122 [Backend] Unohditko salasanan
  client/src/pages/ForgotPassword/ForgotPassword.jsx
  server/mailer.js
  server/models/userModel.js
  server/package.json
  server/routers/userRouter.js
  server/utils/config.js
Labels: Backend :gear:

#121 [Frontend 🖥️] 74 frontend sopimustieto sivun yhteen kokoaminen
  client/src/components/Router/Router.jsx
  client/src/pages/ContractInfo/ContractInfo.jsx
  client/src/pages/ContractInfo/_contractinfo.scss
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#123 Feat/#100/frontend confirmation pop up component
  client/package-lock.json
  client/src/pages/ChooseDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/ChooseDegree/ConfirmSelection/_confirmselection.scss
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#130 Feat/#94/search page backend integration
  client/src/App.js
  client/src/components/PageNumbers/PageNumbers.jsx
  client/src/components/Router/Router.jsx
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/pages/ChooseDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/ChooseDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/ChooseDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/ChooseDegree/SearchPage/SearchPage.jsx
  client/src/utils/context/DegreeContext.jsx
Labels: Frontend :desktop_computer:

#127 [Backend] salasanan vaihtaminen backendissa
  server/models/userModel.js
  server/routers/userRouter.js
Labels: Backend :gear:

#138 Feat/#137/yrityksen-nimenhaku-y-tunnuksella
  server/routers/eReqRouter.js
Labels: Backend :gear:, Feat :new:, Ready for Review 🔍

#140 Feat/#44/frontend salasanan palauttaminen
  client/src/components/Button/Button.jsx
  client/src/components/Button/_button.scss
  client/src/components/Router/Router.jsx
  client/src/pages/ResetPassword/ResetPassword.jsx
  client/src/pages/UpdateHomePageAfterLogin/UpdateHomepageAfterLogin.jsx
  client/src/pages/UpdateHomePageAfterLogin/_updatehomepageafterlogin.scss
  client/src/scss/index.scss
Labels: Ready for Review 🔍, Unassigned ❕, Review Requested 🔍
