Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-09, with the labels that each got.

#245 Feat/#222/backend adding workplace model and router
  server/index.js
  server/models/workplaceModel.js
  server/package-lock.json
  server/routers/workRouter.js
Labels: Backend :gear:, Feat :new:

#247 Feat/#243/added automatic testing environment and its configuration
  server/.gitignore
  server/app.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routers/degreeRouter.js
  server/routers/workplaceRouter.js
  server/tests/auth_api.test.js
  server/tests/teardown.js
  server/tests/test_data.js
  server/utils/config.js
Labels: Backend :gear:, Chore :construction_worker_man:

#251 Feat/#235/frontend update profile page
  client/package-lock.json
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/PasswordInput/PasswordInput.jsx
  client/src/components/PopUpForm/PopUpForm.jsx
  client/src/components/PopUpForm/_popupform.scss
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/ProfilePage/_profilepage.scss
  client/src/scss/index.css.map
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#253 [Backend]: Install and start scrips of repository root
  README.md
  client/package-lock.json
  package-lock.json
  package.json
Labels: Chore :construction_worker_man:

#255 Feat/#228/frontend departments to workplace list
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/_degreeConfirmSelection.scss
  client/src/pages/CompanyInfo/_companyinfo.scss
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/_evaluationworkplace.scss
  client/src/store/evaluationStore.js
  client/src/store/useStore.js
Labels: Feat :new:, Frontend :desktop_computer:

#256 Fix landing page css
  client/src/pages/LandingPage/LandingPage.jsx
  client/src/pages/LandingPage/_landingpage.scss
Labels: BugFix :bug:, Frontend :desktop_computer:

#257 Admin menu
  client/src/components/Router/Router.jsx
  client/src/pages/AdminMenu/AdminMenu.jsx
  client/src/pages/AdminMenu/_adminmenu.scss
  client/src/scss/index.css.map
  client/src/scss/index.scss
Labels: Feat :new:, Frontend :desktop_computer:

#259 Refactor/#232/frontend pagination condition
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
Labels: Frontend :desktop_computer:, Ready for Review 🔍, Refactor :repeat:

#262 Remove unused components from frontend
  client/src/components/DynamicTextFields/DynamicTextFields.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/_footer.scss
  client/src/components/PageNumbers/PageNumbers.jsx
  client/src/components/PageNumbers/_pagenumbers.scss
  client/src/components/Router/Router.jsx
  client/src/pages/ChooseRole/ChooseRole.jsx
  client/src/pages/ChooseRole/_chooserole.scss
  client/src/pages/CreateAccountCustomer/AccountCreated/AccountCreated.jsx
  client/src/pages/CreateAccountCustomer/AccountCreated/_accountcreated.scss
  client/src/pages/CreateAccountCustomer/AccountFailed/AccountFailed.jsx
  client/src/pages/CreateAccountCustomer/AccountFailed/_accountfailed.scss
  client/src/pages/CreateAccountCustomer/GeneralInfo/GeneralInfo.jsx
  client/src/pages/CreateAccountCustomer/GeneralInfo/_generalinfo.scss
  client/src/pages/CreateAccountCustomer/LoginInfo/LoginInfo.jsx
  client/src/pages/CreateAccountCustomer/LoginInfo/_logininfo.scss
  client/src/pages/CreateAccountCustomer/WorkInfo/WorkInfo.jsx
  client/src/pages/CreateAccountCustomer/WorkInfo/_workinfo.scss
  client/src/pages/CreateAccountSupervisor/NotificationSupervisor.jsx
  client/src/pages/CreateAccountSupervisor/RegisterSupervisor.jsx
  client/src/pages/CreateAccountTeacher/NotificationTeacher.jsx
  client/src/pages/CreateAccountTeacher/RegisterTeacher.jsx
  client/src/pages/FirstLogin/Context.js
  client/src/pages/FirstLogin/FirstLogin.jsx
  client/src/pages/FirstLogin/Step0/Step0.jsx
  client/src/pages/FirstLogin/Step0/_pick-account-type.scss
  client/src/pages/FirstLogin/Step1/Step1.jsx
  client/src/pages/FirstLogin/Step2/Step2.jsx
  client/src/pages/FirstLogin/_firstlogin.scss
  client/src/pages/ProtectedRoutes.js
  client/src/pages/RegisterPage/RegisterPage.jsx
  client/src/pages/RegisterPage/_registerpage.scss
  client/src/pages/UserPage/Accomplishments/Accomplishments.jsx
  client/src/pages/UserPage/Degrees/Degrees.jsx
  client/src/pages/UserPage/Teachers/Teachers.jsx
  client/src/pages/UserPage/UserPage.jsx
  client/src/pages/UserPage/_userpage.scss
  client/src/scss/index.css.map
  client/src/scss/index.scss
  client/src/utils/PasswordValidate.js
Labels: Frontend :desktop_computer:, Refactor :repeat:

#261 [Fullstack]: Feat/#101/save load degree tofrom database
  README.md
  client/src/App.js
  client/src/api/degree.js
  client/src/api/workplace.js
  client/src/components/ApiLoader.jsx
  client/src/components/Header/WavesHeader.jsx
  client/src/components/NotificationBadge/NotificationBadge.jsx
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/PasswordInput/PasswordInput.jsx
  client/src/components/Router/Router.jsx
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/components/Stepper/Stepper.jsx
  client/src/components/UserNav/UserNav.jsx
  client/src/pages/ChooseDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/ChooseDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/ChooseDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/ChooseDegree/SearchPage/SearchPage.jsx
  client/src/pages/ChooseDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/ChooseDegree/Summary/Summary.jsx
  client/src/pages/ChooseDegree/UnitInfo/UnitInfo.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/CompanySearchPage.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/TestPage/TestPage.jsx
  client/src/pages/UpdateHomePageAfterLogin/UpdateHomepageAfterLogin.jsx
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/store/context/AuthContext.jsx
  client/src/store/context/CriteriaFieldsContext.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/context/InternalApiContext.jsx
  client/src/store/zustand/evaluationStore.js
  client/src/store/zustand/formStore.js
  client/src/store/zustand/unitsStore.js
  client/src/utils/context/InternalDegreeContext.jsx
  package.json
  server/models/degreeModel.js
  server/routers/degreeRouter.js
  server/routers/workplaceRouter.js
Labels: Backend :gear:, Backlog 📜, Feat :new:, Frontend :desktop_computer:

#265 234 frontend adding a degree administration page to administration section
  client/src/components/Router/Router.jsx
  client/src/components/Searchbar/_searchbar.scss
  client/src/pages/AdminDegree/AddDegree/AddDegree.jsx
  client/src/pages/AdminDegree/AddDegree/_adddegree.scss
  client/src/pages/AdminDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/AdminDegree/ConfirmSelection/_confirmselection.scss
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/DegreeInfo/_degreeinfo.scss
  client/src/pages/AdminDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/AdminDegree/DegreeUnits/_degreeunits.scss
  client/src/pages/AdminDegree/DegreeUnits/unitsTempData.js
  client/src/pages/AdminDegree/SearchPage/SearchPage.jsx
  client/src/pages/AdminDegree/SearchPage/_searchpage.scss
  client/src/pages/AdminDegree/SearchPage/tempData.js
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/AdminDegree/SpecifyTasks/_specifytasks.scss
  client/src/pages/AdminDegree/Summary/Summary.jsx
  client/src/pages/AdminDegree/Summary/_summary.scss
  client/src/pages/AdminDegree/UnitInfo/UnitInfo.jsx
  client/src/pages/AdminDegree/UnitInfo/_unitinfo.scss
  client/src/scss/index.scss
  client/src/store/context/InternalApiContext.jsx
  server/models/userModel.js
Labels: Frontend :desktop_computer:

#264 Feat/#/233 frontend building a clickable page for suoritukset ja tehtävä palautteet section for evaluating the skill level of the client student
  client/src/assets/Vector.png
  client/src/assets/label.png
  client/src/assets/photo.png
  client/src/components/PerformaceFeedback/PerformancesFeedback/PerformancesFeedback.jsx
  client/src/components/PerformaceFeedback/PerformancesFeedback/_performancesfeedback.scss
  client/src/components/PerformaceFeedback/TeacherPerformance/TeacherPerformanceFeedBack.jsx
  client/src/components/PerformaceFeedback/TeacherPerformance/_teacherPerformance.scss
  client/src/components/Router/Router.jsx
  client/src/components/UnitStatus/UnitStatus.jsx
  client/src/pages/LandingPage/_landingpage.scss
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/Performance/UserPerformance/UserPerformance.jsx
  client/src/pages/Performance/UserPerformance/_userperformane.scss
  client/src/pages/TestPage/TestPage.jsx
  client/src/pages/TestPage/_testpage.scss
  client/src/pages/UserDashboard/SimpleAccordion/SimpleAccordion.jsx
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/scss/index.scss
Labels: Done ✔️

#266 Refactor/#224/frontend nav bar
  client/src/components/Router/Router.jsx
  client/src/components/UserNav/UserNav.jsx
  client/src/components/UserNav/_usernav.scss
  client/src/pages/AdminMenu/AdminMenu.jsx
Labels: Frontend :desktop_computer:, Refactor :repeat:

#269 Update teacher & supervisor homepages
  client/src/components/UnitStatus/UnitStatus.jsx
  client/src/pages/UserDashboard/CustomersAccordion/CustomersAccordion.jsx
  client/src/pages/UserDashboard/CustomersAccordion/_customersaccordion.scss
  client/src/pages/UserDashboard/SimpleAccordion/SimpleAccordion.jsx
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#272 Change navbar if customer chosen
  client/src/components/Header/WavesHeader.jsx
  client/src/components/UserNav/UserNav.jsx
  client/src/pages/UserDashboard/CustomerList/CustomerList.jsx
  client/src/pages/UserDashboard/CustomerList/_customerlist.scss
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/scss/index.scss
  client/src/store/zustand/formStore.js
Labels: Frontend :desktop_computer:

#273 Bugfix/#271/frontend fix homepage navigation
  client/src/components/NotificationBadge/NotificationBadge.jsx
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/Router/Router.jsx
  client/src/components/Stepper/Stepper.jsx
  client/src/components/UserNav/UserNav.jsx
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/AdminDegree/Summary/Summary.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/_companyDegreeUnits.scss
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/CompanySearchPage.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/_companyserachpage.scss
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/_evaluationsummary.scss
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/_evaluationworkplace.scss
  client/src/pages/ForgotPassword/_forgotpassword.scss
  client/src/pages/Home/CustomerList/CustomerList.jsx
  client/src/pages/Home/CustomerList/_customerlist.scss
  client/src/pages/Home/UnitList/UnitList.jsx
  client/src/pages/Home/UnitList/_unitlist.scss
  client/src/pages/HomePageAfterLoggedIn/HomePageAfterLoggedIn.jsx
  client/src/pages/HomePageAfterLoggedIn/_homepageafterloggedin.scss
  client/src/pages/LandingPage/_landingpage.scss
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/Performance/UserPerformance/UserPerformance.jsx
  client/src/pages/UpdateHomePageAfterLogin/UpdateHomepageAfterLogin.jsx
  client/src/pages/UpdateHomePageAfterLogin/_updatehomepageafterlogin.scss
  client/src/pages/UserDashboard/CustomerList/CustomerList.jsx
  client/src/pages/UserDashboard/CustomerList/_customerlist.scss
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/pages/UserDashboard/_userdashboard.scss
  client/src/scss/index.css.map
  client/src/scss/index.scss
  client/src/store/zustand/evaluationStore.js
Labels: Frontend :desktop_computer:
