Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-07, with the labels that each got.

#141 Feat/#103/frontend update homepage after login
  client/src/components/Router/Router.jsx
  client/src/scss/index.scss
Labels: In Progress 🚧

#143 [backend]: Creating evaluation collection for database
  server/models/evaluationModel.js
Labels: Backend :gear:, Feat :new:

#184 Feat/#174/frontend add client assignment page
  client/src/components/Router/Router.jsx
  client/src/pages/CreateEvaluation/ActivateEvaluation/ActivateEvaluation.jsx
  client/src/pages/CreateEvaluation/ActivateEvaluation/_activateevaluation.scss
  client/src/pages/CreateEvaluation/CustomerForm/CustomerForm.jsx
  client/src/pages/CreateEvaluation/CustomerForm/_customerform.scss
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationUnits/_evaluationunits.scss
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/_evaluationworkplace.scss
  client/src/scss/index.css.map
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#193 Update the landing flow
  client/src/assets/Helsinki_white_logo.png
  client/src/components/Header/WavesHeader.jsx
  client/src/components/Notification/Notification.jsx
  client/src/pages/ForgotPassword/ForgotPassword.jsx
  client/src/pages/ForgotPassword/_forgotpassword.scss
  client/src/pages/LandingPage/LandingPage.jsx
  client/src/pages/LandingPage/_landingpage.scss
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/LoginPage/_loginpage.scss
  client/src/pages/ResetPassword/ResetPassword.jsx
  client/src/pages/ResetPassword/_resetpassword.scss
  client/src/scss/_base.scss
Labels: Frontend :desktop_computer:, In Progress 🚧

#192 [Backend]: Update eReqRouter to use fetch
  server/package-lock.json
  server/package.json
  server/routers/eReqRouter.js
Labels: Backend :gear:, Ready for Review 🔍, Refactor :repeat:

#194 [Backend]: Refactor userSchema
  server/models/userModel.js
  server/routers/userRouter.js
Labels: Backend :gear:, Refactor :repeat:

#195 Update the logout design and functionality
  client/src/components/Header/WavesHeader.jsx
  client/src/pages/ResetPassword/_resetpassword.scss
Labels: Frontend :desktop_computer:, Done ✔️

#196 Feat/#161/frontend add company name
  client/src/components/Router/Router.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/companyinfo.scss
  client/src/pages/UserDashboard/_userdashboard.scss
  client/src/scss/index.scss
  client/src/useStore.js
  package-lock.json
  package.json
Labels: Frontend :desktop_computer:, Done ✔️

#197 Creating a new company field
  client/src/components/PageNavigationButtons/PageNavigationButtons.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
Labels: Frontend :desktop_computer:, Done ✔️

#198 Feat/#173/frontend evaluation form calendar component
  client/package-lock.json
  client/package.json
  client/src/evaluationStore.js
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/_evaluationform.scss
  package-lock.json
Labels: Frontend :desktop_computer:

#201 [Backend]: Updated API Namepoints in eReqRouter
  server/routers/eReqRouter.js
Labels: Backend :gear:, Ready for Review 🔍, Refactor :repeat:

#202 172(2) frontend degree info over view page editable
  client/package-lock.json
  client/package.json
  client/src/components/Stepper/Stepper.jsx
  client/src/components/Stepper/_stepper.scss
  client/src/pages/ChooseDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/ChooseDegree/DegreeInfo/_degreeinfo.scss
  client/src/pages/ChooseDegree/DegreeUnits/DegreeUnits.jsx
  client/src/scss/index.scss
  client/src/useStore.js
Labels: Frontend :desktop_computer:, Ready for Review 🔍, Review Requested 🔍

#203 Feat/#180/frontend unit page for evaluation flow
  client/package-lock.json
  client/package.json
  client/src/components/Button/Button.jsx
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/components/SelectUnit/_selectunit.scss
  client/src/evaluationStore.js
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/_evaluationsummary.scss
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationUnits/_evaluationunits.scss
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/unitsStore.js
Labels: Frontend :desktop_computer:

#206 Feat/#164/frontend compose the select degree page for company
  client/package-lock.json
  client/src/App.js
  client/src/components/NotificationBadge/NotificationBadge.jsx
  client/src/components/Router/Router.jsx
  client/src/components/UnitStatus/UnitStatus.jsx
  client/src/components/UnitStatus/_unitstatus.scss
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/_companyDegreeUnits.scss
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/CompanySearchPage.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/_companyserachpage.scss
  client/src/pages/CompanyInfo/_companyinfo.scss
  client/src/pages/UserDashboard/UserDashboard.jsx
  client/src/pages/UserDashboard/_userdashboard.scss
  client/src/scss/index.scss
  client/src/utils/context/InternalDegreeContext.jsx
  package-lock.json
  package.json
Labels: Done ✔️
