Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-08, with the labels that each got.

#205 Refactor/#189/frontend env file
  client/.gitignore
  client/src/api/degree.js
  client/src/api/user.js
  client/src/api/workplace.js
  client/src/components/UserNav/UserNav.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CreateAccountCustomer/WorkInfo/WorkInfo.jsx
  client/src/pages/CreateAccountSupervisor/RegisterSupervisor.jsx
  client/src/pages/CreateAccountTeacher/RegisterTeacher.jsx
  client/src/pages/ForgotPassword/ForgotPassword.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/RegisterPage/RegisterPage.jsx
  client/src/pages/ResetPassword/ResetPassword.jsx
  client/src/utils/context/AuthContext.jsx
  client/src/utils/context/DegreeContext.jsx
  client/src/utils/context/InternalDegreeContext.jsx
Labels: Frontend :desktop_computer:, Refactor :repeat:

#209 Feat/#/166 frontend compose the degree unit selection page for company
  client/package-lock.json
  client/src/components/Router/Router.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/_companyDegreeUnits.scss
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/CompanySearchPage.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/_degreeConfirmSelection.scss
  client/src/pages/CompanyInfo/_companyinfo.scss
  client/src/pages/LandingPage/_landingpage.scss
  client/src/pages/LoginPage/_loginpage.scss
  client/src/scss/index.scss
  client/src/store/useStore.js
Labels: Ready for Review 🔍, Unassigned ❕, Review Requested 🔍

#212 [Backend]: Hard-coding Helsingin kaupunki to API
  server/routers/eReqRouter.js
Labels: Backend :gear:, Feat :new:, Ready for Review 🔍

#213 172-3 frontend degree units data editable
  .gitignore
  client/src/App.js
  client/src/components/DynamicTextFields/DynamicTextFields.jsx
  client/src/components/Header/WavesHeader.jsx
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/Router/Router.jsx
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/components/Stepper/_stepper.scss
  client/src/pages/ChooseDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/ChooseDegree/ConfirmSelection/_confirmselection.scss
  client/src/pages/ChooseDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/ChooseDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/ChooseDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/ChooseDegree/SpecifyTasks/_specifytasks.scss
  client/src/pages/ChooseDegree/Summary/Summary.jsx
  client/src/pages/ChooseDegree/Summary/_summary.scss
  client/src/pages/CreateEvaluation/EvaluationForm/_evaluationform.scss
  client/src/scss/index.scss
  client/src/store/unitsStore.js
  client/src/utils/context/CriteriaFieldsContext.jsx
  package-lock.json
  package.json
Labels: Frontend :desktop_computer:

#171 [backend] Update user Schema and relating functions
  server/models/userModel.js
  server/routers/userRouter.js
Labels: Backend :gear:, Feat :new:
