Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-10, with the labels that each got.

#319 swapping the radio button
  client/src/components/PerformaceFeedback/PerformancesFeedback/PerformancesFeedback.jsx
  client/src/components/PerformaceFeedback/TeacherPerformance/TeacherPerformanceFeedBack.jsx
Labels: Done ✔️

#321 Refactor/#310/frontend refactor router according to roles
  client/src/components/Router/Router.jsx
  client/src/pages/AdminDegree/ConfirmSelection/ConfirmSelection.jsx
  client/src/pages/AdminDegree/ConfirmSelection/_confirmselection.scss
  client/src/pages/AdminDegree/UnitInfo/UnitInfo.jsx
  client/src/pages/AdminDegree/UnitInfo/_unitinfo.scss
  client/src/pages/Home/CustomerList/CustomerList.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/scss/index.css.map
  client/src/scss/index.scss
Labels: Frontend :desktop_computer:

#322 Bugfix/#309/frontend fix saving units in add degree
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/pages/AdminDegree/AddDegree/AddDegree.jsx
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/DegreeInfo/_degreeinfo.scss
  client/src/pages/AdminDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/AdminDegree/DegreeUnits/_degreeunits.scss
  client/src/pages/AdminDegree/SearchPage/SearchPage.jsx
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/AdminDegree/SpecifyTasks/_specifytasks.scss
  client/src/pages/AdminDegree/Summary/Summary.jsx
  client/src/pages/AdminDegree/Summary/_summary.scss
  client/src/store/context/CriteriaFieldsContext.jsx
  client/src/store/zustand/formStore.js
  client/src/store/zustand/unitsStore.js
Labels: Frontend :desktop_computer:

#324 Remove the “lisää tiedosto” button & add top padding to feedback form
  client/src/components/PerformaceFeedback/PerformancesFeedback/PerformancesFeedback.jsx
  client/src/components/PerformaceFeedback/PerformancesFeedback/_performancesfeedback.scss
Labels: Frontend :desktop_computer:

#325 Feat/#301/frontend admin menu links
  client/src/App.js
  client/src/pages/AdminDegree/SearchPage/SearchPage.jsx
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/AdminDegree/Summary/Summary.jsx
  client/src/pages/AdminDegree/Summary/_summary.scss
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/store/context/CriteriaFieldsContext.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/zustand/unitsStore.js
Labels: Frontend :desktop_computer:

#330 Removing the täydennettävää element from the list of client tasks
  client/src/components/UnitStatus/UnitStatus.jsx
  client/src/pages/Home/UnitList/UnitList.jsx
Labels: Frontend :desktop_computer:

#332 Update userRouter.js (return userid on creation)
  server/routers/userRouter.js
Labels: Backend :gear:, BugFix :bug:, Done ✔️

#335 Feat/#304/frontend evaluation form dates
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/pages/AdminMenu/AdminMenu.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/store/zustand/evaluationStore.js
  client/src/store/zustand/unitsStore.js
Labels: Frontend :desktop_computer:

#338 Feat/#/287 fullstack create an api connection on the työpaikan lisääminen page estimation 5
  client/src/api/user.js
  client/src/api/workplace.js
  client/src/components/SelectUnit/SelectUnit.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CompanyInfo/CompanySearchPage/CompanySearchPage.jsx
  client/src/pages/CompanyInfo/DegreeConfirmSelection/DegreeConfirmSelection.jsx
  client/src/pages/TestPage/TestPage.jsx
  client/src/store/context/InternalApiContext.jsx
  client/src/store/zustand/formStore.js
  server/models/workplaceModel.js
  server/routers/workplaceRouter.js
Labels: Done ✔️

#339 checking the format of the data
  client/src/pages/CompanyInfo/CompanyInfo.jsx
Labels: Done ✔️

#340 Feat/#323/frontend adding and editing degree units
  client/src/components/PageNavigationButtons/PageNavigationButtons.jsx
  client/src/components/Router/Router.jsx
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/DegreeUnits/DegreeUnits.jsx
  client/src/pages/AdminDegree/EditUnits/EditUnits.jsx
  client/src/pages/AdminDegree/EditUnits/_editunits.scss
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/AdminDegree/Summary/Summary.jsx
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/pages/CompanyInfo/CompanyInfo.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
  client/src/scss/index.scss
  client/src/store/zustand/formStore.js
  client/src/store/zustand/unitsStore.js
  server/models/degreeModel.js
  server/routers/degreeRouter.js
Labels: Frontend :desktop_computer:

#341 290 fullstack check if the forgot password function defined at login works properly estimation 0
  client/src/pages/ResetPassword/_resetpassword.scss
  server/mailer.js
Labels: Backend :gear:, Frontend :desktop_computer:, Ready for Review 🔍, Review Requested 🔍

#348 Feat/#342/frontend replace mockdata in create evaluation
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/pages/AdminMenu/AdminMenu.jsx
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/CreateEvaluation/EvaluationUnits/EvaluationUnits.jsx
  client/src/pages/CreateEvaluation/EvaluationWorkplace/EvaluationWorkplace.jsx
Labels: Frontend :desktop_computer:

#353 [Backend]: Adding the evaluation router
  server/app.js
  server/models/evaluationModel.js
  server/routers/evaluationRouter.js
Labels: Backend :gear:, Feat :new:, Ready for Review 🔍, Review Requested 🔍

#369 Refactor/#359/reducing unnecessary api calls
  client/package.json
  client/src/store/context/AuthContext.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/context/InternalApiContext.jsx
  server/app.js
Labels: Ready for Review 🔍, Unassigned ❕, Review Requested 🔍

#370 Feat/#/360 frontend creating simple loading screen solution estimation 2
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/DegreeUnits/DegreeUnits.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/context/InternalApiContext.jsx
  server/app.js
Labels: Ready for Review 🔍, Unassigned ❕, Review Requested 🔍
