Repository VirittamoHelsinki/saukko-app, pull requests merged in 2023-11, with the labels that each got.

#371 Changing the text
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/context/InternalApiContext.jsx
  server/app.js
Labels: Done ✔️

#372 [Backend]: Quickfix to evaluationModel.js
  server/models/evaluationModel.js
Labels: Backend :gear:, BugFix :bug:, Done ✔️

#373 Feat/#288/evaluation api connection
  client/src/api/evaluation.js
  client/src/pages/CreateEvaluation/EvaluationSummary/EvaluationSummary.jsx
  client/src/pages/Home/CustomerList/CustomerList.jsx
  client/src/store/context/InternalApiContext.jsx
  server/models/userModel.js
  server/routers/userRouter.js
Labels: Frontend :desktop_computer:

#374 Feat/#292/update home page to show actual data
  client/src/api/evaluation.js
  client/src/components/UnitStatus/UnitStatus.jsx
  client/src/components/UserNav/UserNav.jsx
  client/src/pages/AdminMenu/AdminMenu.jsx
  client/src/pages/Home/CustomerList/CustomerList.jsx
  client/src/pages/Home/UnitList/UnitList.jsx
  client/src/store/context/ExternalApiContext.jsx
  client/src/store/context/InternalApiContext.jsx
  client/src/store/zustand/evaluationStore.js
  client/src/store/zustand/formStore.js
Labels: Frontend :desktop_computer:

#380 Feat/#/378 frontend bug fix for company degree units
  client/src/pages/CompanyInfo/CompanyDegreeUnits/CompanyDegreeUnits.jsx
  client/src/store/context/InternalApiContext.jsx
Labels: Done ✔️
