Repository VirittamoHelsinki/saukko-app, pull requests merged in 2024-04, with the labels that each got.

#451 Frontend 🖥️ - SA-216/modify the header wave according to figma
  client/src/components/Header/WavesHeader.jsx
  client/src/components/Header/_wavesheader.scss
  client/src/components/PerformaceFeedback/PerformancesFeedback/PerformancesFeedback.jsx
  client/src/components/PerformaceFeedback/TeacherPerformance/TeacherPerformanceFeedBack.jsx
  client/src/pages/Home/CustomerList/CustomerList.jsx
  client/src/pages/Home/CustomerList/_customerlist.scss
  client/src/pages/Home/UnitList/UnitList.jsx
  client/src/pages/Home/UnitList/_unitlist.scss
  client/src/pages/Performance/UserPerformance/UserPerformance.jsx
  client/src/pages/Performance/UserPerformance/_userperformane.scss
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/ProfilePage/_profilepage.scss
Labels: Frontend :desktop_computer:, Ready for Review 🔍

#450 BACKEND ⚙Sa233 fix bug that allow change password without knowig current one
  client/src/api/user.js
  client/src/pages/ProfilePage/ProfilePage.jsx
  server/src/controllers/authController.ts
  server/src/index.ts
  server/src/models/userModel.ts
  server/src/routers/authRouter.ts
Labels: Backend :gear:, Ready for Review 🔍

#452 Frontend 🖥️- Implement Error boundary component
  client/src/App.js
  client/src/components/Router/Router.jsx
  client/src/components/errorBoundary.jsx
Labels: Frontend :desktop_computer:, Ready for Review 🔍

#453 BACKEND ⚙ | Frontend 🖥️ - Sa122 sa146 improve evaluation data endpoints and usability
  client/src/api/evaluation.js
  client/src/store/context/InternalApiContext.jsx
  server/src/controllers/evaluationController.ts
  server/src/routers/evaluationRouter.ts
Labels: Backend :gear:, Frontend :desktop_computer:, Ready for Review 🔍

#454 Update logout method to remove auth state cookie
  server/src/controllers/authController.ts
Labels: Backend :gear:, Ready for Review 🔍

#458 create server build script, update ci process to build and start server
  dockerfile
  package.json
  server/.gitignore
  server/package.json
  server/tsconfig.json
Labels: Backend :gear:, Ready for Review 🔍

#486 Fix broken ePerusteet api call, update MUI versions
  client/package-lock.json
  client/package.json
  client/src/components/Router/Router.jsx
  client/src/pages/AdminDegree/DegreeInfo/DegreeInfo.jsx
  client/src/pages/AdminDegree/SpecifyTasks/SpecifyTasks.jsx
  client/src/pages/CreateEvaluation/EvaluationForm/EvaluationForm.jsx
  server/src/controllers/eReqController.ts
Labels: Backend :gear:

#488 Update server build script for fix azure deploy workflow
  server/package.json
Labels: Ready for Review 🔍

#501 fix possible problem
  server/src/middlewares/middleware.tokens.ts
Labels: Backend :gear:

#505 SA 326/add saving comment for teacher in Suoritukset-ja-Tehtavat page
  client/src/components/NotificationModal/NotificationModal.jsx
  client/src/components/PerformaceFeedback/TeacherPerformance/TeacherPerformanceFeedBack.jsx
  client/src/components/RequirementsAndCriteriaModal/RequirementsAndCriteriaModal.jsx
  client/src/pages/Performance/UserPerformance/UserPerformance.jsx
  server/src/models/evaluatuionModel.ts
Labels: Backend :gear:, Frontend :desktop_computer:

#530 SA 400 - clarify the displaying feature on ATV criteria in suoritukset page
  client/src/components/RequirementsAndCriteriaModal/RequirementsAndCriteriaModal.jsx
Labels: Frontend :desktop_computer:
